--- #YAML:1.0
name:                   WWW-Scraper-ISBN-WHSmith_Driver
version:                0.02
abstract:               Search driver for the WHSmith online book catalog
author:
  - Barbie <barbie@cpan.org>

license:                perl
distribution_type:      module
installdirs:            site

requires:
  perl:                         5.006
  Test::More:                   0.70
  WWW::Mechanize:               1.60
  WWW::Scraper::ISBN:           0.25
  WWW::Scraper::ISBN::Driver:   0.18
recommends:
  Test::Pod:                    1.00
  Test::Pod::Coverage:          0.08
  Test::CPAN::Meta:             0
  Test::CPAN::Meta::JSON:       0
build_requires:
  IO::File:                     0
  Test::More:                   0.70

provides:
  WWW::Scraper::ISBN::WHSmith_Driver:
    file:     lib/WWW/Scraper/ISBN/WHSmith_Driver.pm
    version:  0.02
no_index:
  directory:
    - t
    - examples

meta-spec:
   version:   1.4
   url:       http://module-build.sourceforge.net/META-spec-v1.4.html
generated_by: Hand 1.0
